baseURL = 'https://mlange-42.github.io/arche-demo/'
languageCode = 'en-us'
title = 'Arche Demo'

[params]
custom_css = ["css/style.css", "css/sidebar.css"]
custom_js = ["js/wasm_exec.js"]

repository = "https://github.com/mlange-42/arche-demo"

about = """{{< u >}}About{{< /u >}}  
[Arche](https://github.com/mlange-42/arche) is an archetype-based
Entity Component System (ECS) for Go.
"""
