name: Publish

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: 
  contents: write

env:
  GOOS: js
  GOARCH: wasm

jobs:

  build:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get ./...

      - name: Build WebAssembly
        run: |
          go build -tags tiny -o docs/static/wasm/logo.wasm ./logo/main
          go build -tags tiny -o docs/static/wasm/box2d.wasm ./box2d/main
          go build -tags tiny -o docs/static/wasm/bees.wasm ./bees/main
          go build -tags tiny -o docs/static/wasm/ants.wasm ./ants/main

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.0'
      - name: Build Site
        run: hugo -s docs
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: docs/public
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
